
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vidhi
 */

/* This form will allow the user to input the data of each volunteer of the Kennel, which is saved along with the ID of the volunteer, which is automatically generated (primary key).
*/

public class newvolunteer extends javax.swing.JPanel {

    /**
     * Creates new form newvolunteer
     */
    public newvolunteer() {
        initComponents();
        doe1.setVisible(false);
        t1.setVisible(false);
        t1.setSelected(true);
        num.setEditable(false);

        try {
            FileReader idf = new FileReader("volid.txt");
            BufferedReader idFile = new BufferedReader(idf);
            int idg = Integer.parseInt(idFile.readLine());
            idg = idg + 1;
            num.setText("" + idg);
        } catch (Exception error) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nam = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        ei = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        mn = new javax.swing.JLabel();
        numb = new javax.swing.JTextField();
        ds1 = new javax.swing.JLabel();
        da = new com.toedter.calendar.JDateChooser();
        ag1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        rfv = new javax.swing.JLabel();
        cas = new javax.swing.JRadioButton();
        doe = new javax.swing.JRadioButton();
        wish = new javax.swing.JRadioButton();
        school1 = new javax.swing.JLabel();
        sch = new javax.swing.JTextField();
        doe1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        wish1 = new javax.swing.JLabel();
        walk = new javax.swing.JCheckBox();
        ken = new javax.swing.JCheckBox();
        train = new javax.swing.JCheckBox();
        fandb = new javax.swing.JCheckBox();
        sale = new javax.swing.JCheckBox();
        t1 = new javax.swing.JRadioButton();
        idn = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Chalkboard", 0, 24)); // NOI18N
        jLabel3.setText("Details of the new dog");

        jLabel5.setFont(new java.awt.Font("Chalkboard", 0, 24)); // NOI18N
        jLabel5.setText("Details of the new ");

        jLabel9.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        jLabel9.setText("Email id:");

        jLabel19.setText("*Combobox will only show if DOE is selected");

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel4.setFont(new java.awt.Font("Chalkboard", 0, 24)); // NOI18N
        jLabel4.setText("Details of the New ");

        jLabel6.setFont(new java.awt.Font("Chalkboard", 0, 24)); // NOI18N
        jLabel6.setText("Volunteer");

        nam.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        nam.setText("Name:");

        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });

        ei.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        ei.setText("Email id:");

        age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFocusGained(evt);
            }
        });

        mn.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        mn.setText("Mobile Number:");

        numb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numbFocusGained(evt);
            }
        });

        ds1.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        ds1.setText("Date Started:");

        da.setDateFormatString("dd/MM/yyyy");
        da.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                daPropertyChange(evt);
            }
        });

        ag1.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        ag1.setText("Age:");

        id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idFocusGained(evt);
            }
        });

        rfv.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        rfv.setText("Reason for Volunteering:");

        buttonGroup1.add(cas);
        cas.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        cas.setText("CAS");
        cas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casActionPerformed(evt);
            }
        });

        buttonGroup1.add(doe);
        doe.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        doe.setText("DOE");
        doe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doeActionPerformed(evt);
            }
        });

        buttonGroup1.add(wish);
        wish.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        wish.setText("Just wishes to volunteer");
        wish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wishActionPerformed(evt);
            }
        });

        school1.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        school1.setText("School:");

        sch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                schFocusGained(evt);
            }
        });
        sch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schActionPerformed(evt);
            }
        });
        sch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                schKeyReleased(evt);
            }
        });

        doe1.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        doe1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bronze", "Silver", "Gold" }));

        jButton1.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        wish1.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        wish1.setText("What he/she wishes to do:");

        walk.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        walk.setText("Dog walking");
        walk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkActionPerformed(evt);
            }
        });

        ken.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        ken.setText("Working at kennels");
        ken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kenActionPerformed(evt);
            }
        });

        train.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        train.setText("Dog training sessions");
        train.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainActionPerformed(evt);
            }
        });

        fandb.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        fandb.setText("Market faires and bazaars");
        fandb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fandbActionPerformed(evt);
            }
        });

        sale.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        sale.setText("Conducting book sales");
        sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleActionPerformed(evt);
            }
        });

        buttonGroup1.add(t1);
        t1.setText("t");

        idn.setFont(new java.awt.Font("Chalkboard", 0, 14)); // NOI18N
        idn.setText("ID Number:");

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/Rajul/Downloads/logo.gif")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Chalkboard SE", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Add a new volunteer to the system");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(idn)
                .addGap(80, 80, 80)
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(nam)
                .addGap(113, 113, 113)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ag1)
                .addGap(124, 124, 124)
                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(school1)
                .addGap(106, 106, 106)
                .addComponent(sch, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(mn)
                .addGap(54, 54, 54)
                .addComponent(numb, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ei)
                .addGap(99, 99, 99)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ds1)
                .addGap(64, 64, 64)
                .addComponent(da, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rfv))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(cas)
                .addGap(12, 12, 12)
                .addComponent(doe)
                .addGap(6, 6, 6)
                .addComponent(wish))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(doe1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(wish1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(walk)
                .addGap(6, 6, 6)
                .addComponent(fandb))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(train)
                .addGap(6, 6, 6)
                .addComponent(ken))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(sale))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel6)
                                .addGap(0, 0, 0)
                                .addComponent(t1))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(t1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idn)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nam)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(ag1))
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(school1))
                    .addComponent(sch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(mn))
                    .addComponent(numb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(ei))
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ds1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(da, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rfv)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cas)
                    .addComponent(doe)
                    .addComponent(wish))
                .addGap(6, 6, 6)
                .addComponent(doe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(wish1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(walk)
                    .addComponent(fandb))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(train)
                    .addComponent(ken))
                .addGap(6, 6, 6)
                .addComponent(sale)
                .addGap(6, 6, 6)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void casActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casActionPerformed
        if (cas.isSelected()) {
            doe1.setVisible(false);

            rfv.setText("Reason for Volunteering:");
            rfv.setForeground(Color.black);
        }
    }//GEN-LAST:event_casActionPerformed

    private void doeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doeActionPerformed
        if (doe.isSelected()) {
            doe1.setVisible(true);
            rfv.setText("Reason for Volunteering:");
            rfv.setForeground(Color.black);
        }

    }//GEN-LAST:event_doeActionPerformed

    private void schActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schActionPerformed

    private void wishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wishActionPerformed
        if (wish.isSelected()) {
            doe1.setVisible(false);
            rfv.setText("Reason for Volunteering:");
            rfv.setForeground(Color.black);
        }
    }//GEN-LAST:event_wishActionPerformed

    private void walkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkActionPerformed
        wish1.setText("What he/she wishes to do:");
        wish1.setForeground(Color.black);

    }//GEN-LAST:event_walkActionPerformed

    private void saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleActionPerformed
        wish1.setText("What he/she wishes to do:");
        wish1.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_saleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String na = name.getText();
        String a = age.getText();
        String school = sch.getText();
        String mob = numb.getText();
        String em = id.getText();
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        Date das = da.getDate();
        String ans = "";
        String x;
        String idtosave = num.getText();
        boolean er = false;
        boolean ess = false;
        int es = 0;
        int l = mob.length();
        int l5 = em.length();
        for (int i = 0; i < l; i++) {
            x = mob.substring(i, i + 1);
            if (x.matches("[a-zA-Z]+")) {
                ess = true;

            }
        }
        
        for (int i = 0; i < l5; i++) {
            x = em.substring(i, i + 1);
            if (x.equals("@")) {
                es = es+1;

            }
        }
        if (es==0){
            er = true;
            javax.swing.JOptionPane.showMessageDialog(null, "Email ID is Invalid", "Message:ERROR!", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
            ei.setText("* Email id:");
            ei.setForeground(Color.red);
        }
        if (ess == true) {
            er = true;
            javax.swing.JOptionPane.showMessageDialog(null, "Mobile Number is Invalid", "Message:ERROR!", javax.swing.JOptionPane.ERROR_MESSAGE);
           mn.setText("* Mobile Number:");
            mn.setForeground(Color.red);
        }

        if (na.equals("")) {
            er = true;
            nam.setText("* Name:");
            nam.setForeground(Color.red);

        }
        if (a.equals("")) {
            er = true;
            ag1.setText("* Age:");
            ag1.setForeground(Color.red);
        }
        if (school.equals("")) {
            er = true;
            school1.setText("* School:");
            school1.setForeground(Color.red);
        }
        if (mob.equals("")) {
            er = true;
            mn.setText("* Mobile Number:");
            mn.setForeground(Color.red);
        }
        if (em.equals("")) {
            er = true;
            ei.setText("* Email id:");
            ei.setForeground(Color.red);
        }
        if (das == null) {
            er = true;
            ds1.setText("* Date Started:");
            ds1.setForeground(Color.red);
        }
        if (t1.isSelected()) {
            er = true;
            rfv.setText("* Reason for Volunteering:");
            rfv.setForeground(Color.red);
        }
        if (!(walk.isSelected() == true) && !(fandb.isSelected() == true) && !(train.isSelected() == true) 
                && !(ken.isSelected() == true) && !(sale.isSelected() == true)) {
            er = true;
            wish1.setText("* What he/she wishes to do:");
            wish1.setForeground(Color.red);
        }
        if (er == true) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please complete all fields", "Message:ERROR!", 
            javax.swing.JOptionPane.ERROR_MESSAGE);

        }
        if (er == false) {

            String ds = format.format(das);

            if (walk.isSelected() == true) {
                ans = ans + "Dog walking" + "|";
            }
            if (fandb.isSelected() == true) {
                ans = ans + "Market faires and bazaars" + "|";
            }
            if (train.isSelected() == true) {
                ans = ans + "Dog training sessions" + "|";
            }
            if (ken.isSelected() == true) {
                ans = ans + "Working at kennels" + "|";
            }
            if (sale.isSelected() == true) {
                ans = ans + "Conducting book sales" + "|";
            }

            try {
                FileWriter vol = new FileWriter("Volunteers.txt", true);
                PrintWriter volun = new PrintWriter(vol);
                if (cas.isSelected()) {
                    volun.println(idtosave + "|" + na + "|" + a + "|" + school + "|" + mob + "|" + em + "|" + ds + "|" + ans + "CAS");
                }
                if (doe.isSelected()) {
                    String bsg = "" + doe1.getSelectedItem();
                    volun.println(idtosave + "|" + na + "|" + a + "|" + school + "|" + mob + "|" + em + "|" + ds + "|" + ans + "DOE" + "-" + bsg);
                }
                if (wish.isSelected()) {
                    volun.println(idtosave + "|" + na + "|" + a + "|" + school + "|" + mob + "|" + em + "|" + ds + "|" + ans + "Just wishes to volunteer");
                }
                volun.close();
                FileWriter ids = new FileWriter("volid.txt", false);
                PrintWriter idsave = new PrintWriter(ids);
                idsave.println(idtosave);
                idsave.close();

                try {
                    FileReader idf = new FileReader("volid.txt");
                    BufferedReader idFile = new BufferedReader(idf);
                    int idg = Integer.parseInt(idFile.readLine());
                    idg = idg + 1;
                    num.setText("" + idg);
                    idFile.close();
                } catch (Exception error) {

                }
            } catch (Exception error) {

            }
            name.setText("");
            age.setText("");
            sch.setText("");
            numb.setText("");
            id.setText("");
            da.setDate(null);
            t1.setSelected(true);
            walk.setSelected(false);
            sale.setSelected(false);
            fandb.setSelected(false);
            train.setSelected(false);
            ken.setSelected(false);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained

        nam.setText("Name:");
        nam.setForeground(Color.black);

        // TODO add your handling code here:
    }//GEN-LAST:event_nameFocusGained

    private void ageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusGained

        ag1.setText("Age:");
        ag1.setForeground(Color.black);

        // TODO add your handling code here:
    }//GEN-LAST:event_ageFocusGained

    private void schFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_schFocusGained

        school1.setText("School:");
        school1.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_schFocusGained

    private void numbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numbFocusGained
        mn.setText("Mobile Number:");
        mn.setForeground(Color.black);
        // TODO add your handling code here:
    }//GEN-LAST:event_numbFocusGained

    private void idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusGained

        ei.setText("Email id:");
        ei.setForeground(Color.black);// TODO add your handling code here:
    }//GEN-LAST:event_idFocusGained

    private void daPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_daPropertyChange
        ds1.setText("Date Started:");
        ds1.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_daPropertyChange

    private void fandbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fandbActionPerformed
        wish1.setText("What he/she wishes to do:");
        wish1.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_fandbActionPerformed

    private void trainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainActionPerformed
        wish1.setText("What he/she wishes to do:");
        wish1.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_trainActionPerformed

    private void kenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kenActionPerformed
        wish1.setText("What he/she wishes to do:");
        wish1.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_kenActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
String t = name.getText();
        if (!(t.equals(""))){

        int l1 = t.length();
        String  x = (t.substring(0,1)).toUpperCase();

        String y = "";
        for (int i= 1;i<l1;i++){
        y = y + (t.substring(i,i+1)) ;  
            

        }
        name.setText(x+y);     }   // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyReleased

    private void schKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_schKeyReleased
String t = sch.getText();
        if (!(t.equals(""))){

        int l1 = t.length();
        String  x = (t.substring(0,1)).toUpperCase();

        String y = "";
        for (int i= 1;i<l1;i++){
        y = y + (t.substring(i,i+1)) ;  
            

        }
        sch.setText(x+y);   }     // TODO add your handling code here:
    }//GEN-LAST:event_schKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ag1;
    private javax.swing.JTextField age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cas;
    private com.toedter.calendar.JDateChooser da;
    private javax.swing.JRadioButton doe;
    private javax.swing.JComboBox doe1;
    private javax.swing.JLabel ds1;
    private javax.swing.JLabel ei;
    private javax.swing.JCheckBox fandb;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JCheckBox ken;
    private javax.swing.JLabel mn;
    private javax.swing.JLabel nam;
    private javax.swing.JTextField name;
    private javax.swing.JTextField num;
    private javax.swing.JTextField numb;
    private javax.swing.JLabel rfv;
    private javax.swing.JCheckBox sale;
    private javax.swing.JTextField sch;
    private javax.swing.JLabel school1;
    private javax.swing.JRadioButton t1;
    private javax.swing.JCheckBox train;
    private javax.swing.JCheckBox walk;
    private javax.swing.JRadioButton wish;
    private javax.swing.JLabel wish1;
    // End of variables declaration//GEN-END:variables
}
